export const DARK_MAP_STYLE = [
  { elementType: 'geometry',              stylers: [{ color: '#0A0A0F' }] },
  { elementType: 'labels.text.stroke',    stylers: [{ color: '#0A0A0F' }] },
  { elementType: 'labels.text.fill',      stylers: [{ color: '#55556A' }] },
  { featureType: 'administrative',        elementType: 'labels.text.fill', stylers: [{ color: '#7A7A95' }] },
  { featureType: 'road',                  elementType: 'geometry',         stylers: [{ color: '#1E1E26' }] },
  { featureType: 'road',                  elementType: 'geometry.stroke',  stylers: [{ color: '#08080A' }] },
  { featureType: 'road',                  elementType: 'labels.text.fill', stylers: [{ color: '#7A7A95' }] },
  { featureType: 'road.highway',          elementType: 'geometry',         stylers: [{ color: '#252530' }] },
  { featureType: 'road.highway',          elementType: 'geometry.stroke',  stylers: [{ color: '#1E1E26' }] },
  { featureType: 'road.highway',          elementType: 'labels.text.fill', stylers: [{ color: '#F5A623' }] },
  { featureType: 'water',                 elementType: 'geometry',         stylers: [{ color: '#05050A' }] },
  { featureType: 'water',                 elementType: 'labels.text.fill', stylers: [{ color: '#3B82F6' }] },
  { featureType: 'poi',                   elementType: 'geometry',         stylers: [{ color: '#0D0D14' }] },
  { featureType: 'poi',                   elementType: 'labels.text.fill', stylers: [{ color: '#55556A' }] },
  { featureType: 'poi.park',              elementType: 'geometry',         stylers: [{ color: '#0A0D0A' }] },
  { featureType: 'transit',               elementType: 'geometry',         stylers: [{ color: '#1E1E26' }] },
  { featureType: 'transit.station',       elementType: 'labels.text.fill', stylers: [{ color: '#F5A623' }] },
];
